[package]
name = "muell_bot"
version = "1.0.3"
authors = ["Michael Kreuzer <m-git@kreuzers.org>"]

[dependencies]
reqwest = "0.9"
serde = "1"
serde_derive = "1"
serde_json = "1"
iron = "0.6"
router = "0.6"
chrono = { version = "0.4", features = ["serde"]}
